// SPDX-License-Identifier: Apache-2.0
//
// integrity.proto — public gRPC API contract for the Integrity Framework.
//
// NOTE: This file is licensed Apache-2.0, which DIFFERS from the
// repository's top-level AGPL-3.0 license. See api/proto/LICENSE and
// api/proto/README.md for the rationale (this is the public API contract;
// it is intentionally permissive so any client may be built against it).
// This API describes ONLY the open-core daemon; it does not expose any
// proprietary/enterprise features.
//
// Copyright (C) 2026 Sulayman Seid Ymam
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: api/proto/integrity.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntegrityService_GetStatus_FullMethodName       = "/integrity.v1.IntegrityService/GetStatus"
	IntegrityService_StreamEvents_FullMethodName    = "/integrity.v1.IntegrityService/StreamEvents"
	IntegrityService_ListEvents_FullMethodName      = "/integrity.v1.IntegrityService/ListEvents"
	IntegrityService_AddWhitelist_FullMethodName    = "/integrity.v1.IntegrityService/AddWhitelist"
	IntegrityService_RemoveWhitelist_FullMethodName = "/integrity.v1.IntegrityService/RemoveWhitelist"
	IntegrityService_ListWhitelist_FullMethodName   = "/integrity.v1.IntegrityService/ListWhitelist"
	IntegrityService_GetStats_FullMethodName        = "/integrity.v1.IntegrityService/GetStats"
)

// IntegrityServiceClient is the client API for IntegrityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegrityServiceClient interface {
	// Health, TPM state, mode, counters.
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Real-time stream of execution events (server-streaming).
	StreamEvents(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecEvent], error)
	// Query historical events with optional filters.
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// Trusted-hash (whitelist) management.
	AddWhitelist(ctx context.Context, in *WhitelistEntry, opts ...grpc.CallOption) (*WhitelistResponse, error)
	RemoveWhitelist(ctx context.Context, in *RemoveWhitelistRequest, opts ...grpc.CallOption) (*WhitelistResponse, error)
	ListWhitelist(ctx context.Context, in *ListWhitelistRequest, opts ...grpc.CallOption) (*ListWhitelistResponse, error)
	// Aggregate statistics.
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type integrityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrityServiceClient(cc grpc.ClientConnInterface) IntegrityServiceClient {
	return &integrityServiceClient{cc}
}

func (c *integrityServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, IntegrityService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrityServiceClient) StreamEvents(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IntegrityService_ServiceDesc.Streams[0], IntegrityService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, ExecEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntegrityService_StreamEventsClient = grpc.ServerStreamingClient[ExecEvent]

func (c *integrityServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, IntegrityService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrityServiceClient) AddWhitelist(ctx context.Context, in *WhitelistEntry, opts ...grpc.CallOption) (*WhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhitelistResponse)
	err := c.cc.Invoke(ctx, IntegrityService_AddWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrityServiceClient) RemoveWhitelist(ctx context.Context, in *RemoveWhitelistRequest, opts ...grpc.CallOption) (*WhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhitelistResponse)
	err := c.cc.Invoke(ctx, IntegrityService_RemoveWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrityServiceClient) ListWhitelist(ctx context.Context, in *ListWhitelistRequest, opts ...grpc.CallOption) (*ListWhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWhitelistResponse)
	err := c.cc.Invoke(ctx, IntegrityService_ListWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrityServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, IntegrityService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrityServiceServer is the server API for IntegrityService service.
// All implementations must embed UnimplementedIntegrityServiceServer
// for forward compatibility.
type IntegrityServiceServer interface {
	// Health, TPM state, mode, counters.
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	// Real-time stream of execution events (server-streaming).
	StreamEvents(*StreamRequest, grpc.ServerStreamingServer[ExecEvent]) error
	// Query historical events with optional filters.
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// Trusted-hash (whitelist) management.
	AddWhitelist(context.Context, *WhitelistEntry) (*WhitelistResponse, error)
	RemoveWhitelist(context.Context, *RemoveWhitelistRequest) (*WhitelistResponse, error)
	ListWhitelist(context.Context, *ListWhitelistRequest) (*ListWhitelistResponse, error)
	// Aggregate statistics.
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedIntegrityServiceServer()
}

// UnimplementedIntegrityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntegrityServiceServer struct{}

func (UnimplementedIntegrityServiceServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedIntegrityServiceServer) StreamEvents(*StreamRequest, grpc.ServerStreamingServer[ExecEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedIntegrityServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedIntegrityServiceServer) AddWhitelist(context.Context, *WhitelistEntry) (*WhitelistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWhitelist not implemented")
}
func (UnimplementedIntegrityServiceServer) RemoveWhitelist(context.Context, *RemoveWhitelistRequest) (*WhitelistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWhitelist not implemented")
}
func (UnimplementedIntegrityServiceServer) ListWhitelist(context.Context, *ListWhitelistRequest) (*ListWhitelistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWhitelist not implemented")
}
func (UnimplementedIntegrityServiceServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedIntegrityServiceServer) mustEmbedUnimplementedIntegrityServiceServer() {}
func (UnimplementedIntegrityServiceServer) testEmbeddedByValue()                          {}

// UnsafeIntegrityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrityServiceServer will
// result in compilation errors.
type UnsafeIntegrityServiceServer interface {
	mustEmbedUnimplementedIntegrityServiceServer()
}

func RegisterIntegrityServiceServer(s grpc.ServiceRegistrar, srv IntegrityServiceServer) {
	// If the following call panics, it indicates UnimplementedIntegrityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntegrityService_ServiceDesc, srv)
}

func _IntegrityService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrityServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrityService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrityServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrityService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntegrityServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamRequest, ExecEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntegrityService_StreamEventsServer = grpc.ServerStreamingServer[ExecEvent]

func _IntegrityService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrityServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrityService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrityServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrityService_AddWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhitelistEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrityServiceServer).AddWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrityService_AddWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrityServiceServer).AddWhitelist(ctx, req.(*WhitelistEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrityService_RemoveWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrityServiceServer).RemoveWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrityService_RemoveWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrityServiceServer).RemoveWhitelist(ctx, req.(*RemoveWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrityService_ListWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrityServiceServer).ListWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrityService_ListWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrityServiceServer).ListWhitelist(ctx, req.(*ListWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrityService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrityServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntegrityService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrityServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntegrityService_ServiceDesc is the grpc.ServiceDesc for IntegrityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntegrityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "integrity.v1.IntegrityService",
	HandlerType: (*IntegrityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _IntegrityService_GetStatus_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _IntegrityService_ListEvents_Handler,
		},
		{
			MethodName: "AddWhitelist",
			Handler:    _IntegrityService_AddWhitelist_Handler,
		},
		{
			MethodName: "RemoveWhitelist",
			Handler:    _IntegrityService_RemoveWhitelist_Handler,
		},
		{
			MethodName: "ListWhitelist",
			Handler:    _IntegrityService_ListWhitelist_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _IntegrityService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _IntegrityService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/integrity.proto",
}
