// SPDX-License-Identifier: Apache-2.0
//
// integrity.proto — public gRPC API contract for the Integrity Framework.
//
// NOTE: This file is licensed Apache-2.0, which DIFFERS from the
// repository's top-level AGPL-3.0 license. See api/proto/LICENSE and
// api/proto/README.md for the rationale (this is the public API contract;
// it is intentionally permissive so any client may be built against it).
// This API describes ONLY the open-core daemon; it does not expose any
// proprietary/enterprise features.
//
// Copyright (C) 2026 Sulayman Seid Ymam
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/proto/integrity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verdict is the decision the daemon reached for an execution event.
type Verdict int32

const (
	Verdict_VERDICT_UNKNOWN    Verdict = 0
	Verdict_VERDICT_ALLOW      Verdict = 1 // permitted (matched a trust tier)
	Verdict_VERDICT_BLOCK      Verdict = 2 // denied (untrusted; enforced via BPF LSM)
	Verdict_VERDICT_QUARANTINE Verdict = 3 // isolated rather than outright blocked
	Verdict_VERDICT_SUSPICIOUS Verdict = 4 // allowed but flagged (e.g. anomalous behavior)
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNKNOWN",
		1: "VERDICT_ALLOW",
		2: "VERDICT_BLOCK",
		3: "VERDICT_QUARANTINE",
		4: "VERDICT_SUSPICIOUS",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNKNOWN":    0,
		"VERDICT_ALLOW":      1,
		"VERDICT_BLOCK":      2,
		"VERDICT_QUARANTINE": 3,
		"VERDICT_SUSPICIOUS": 4,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_integrity_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_api_proto_integrity_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{0}
}

// ExecEvent is emitted when a process attempts to execute.
type ExecEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // nanoseconds since boot (kernel time)
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Comm          string                 `protobuf:"bytes,4,opt,name=comm,proto3" json:"comm,omitempty"`         // short process name
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"` // path of the binary being executed
	Sha256        []byte                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`     // content hash of the binary
	Verdict       Verdict                `protobuf:"varint,7,opt,name=verdict,proto3,enum=integrity.v1.Verdict" json:"verdict,omitempty"`
	TrustReason   string                 `protobuf:"bytes,8,opt,name=trust_reason,json=trustReason,proto3" json:"trust_reason,omitempty"` // which tier resolved it, or why it was blocked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecEvent) Reset() {
	*x = ExecEvent{}
	mi := &file_api_proto_integrity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEvent) ProtoMessage() {}

func (x *ExecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEvent.ProtoReflect.Descriptor instead.
func (*ExecEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{0}
}

func (x *ExecEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ExecEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ExecEvent) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ExecEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ExecEvent) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExecEvent) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *ExecEvent) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNKNOWN
}

func (x *ExecEvent) GetTrustReason() string {
	if x != nil {
		return x.TrustReason
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_integrity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{1}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	UptimeS       uint64                 `protobuf:"varint,2,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	TpmPresent    bool                   `protobuf:"varint,3,opt,name=tpm_present,json=tpmPresent,proto3" json:"tpm_present,omitempty"`
	TpmState      string                 `protobuf:"bytes,4,opt,name=tpm_state,json=tpmState,proto3" json:"tpm_state,omitempty"` // e.g. "ok", "unsealed", "fallback-hmac"
	EventsTotal   uint64                 `protobuf:"varint,5,opt,name=events_total,json=eventsTotal,proto3" json:"events_total,omitempty"`
	EventsBlocked uint64                 `protobuf:"varint,6,opt,name=events_blocked,json=eventsBlocked,proto3" json:"events_blocked,omitempty"`
	Mode          string                 `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"` // learning | permissive | enforcing | lockdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_integrity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetUptimeS() uint64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

func (x *StatusResponse) GetTpmPresent() bool {
	if x != nil {
		return x.TpmPresent
	}
	return false
}

func (x *StatusResponse) GetTpmState() string {
	if x != nil {
		return x.TpmState
	}
	return ""
}

func (x *StatusResponse) GetEventsTotal() uint64 {
	if x != nil {
		return x.EventsTotal
	}
	return 0
}

func (x *StatusResponse) GetEventsBlocked() uint64 {
	if x != nil {
		return x.EventsBlocked
	}
	return 0
}

func (x *StatusResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_api_proto_integrity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{3}
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	SinceNs       uint64                 `protobuf:"varint,2,opt,name=since_ns,json=sinceNs,proto3" json:"since_ns,omitempty"`
	VerdictFilter Verdict                `protobuf:"varint,3,opt,name=verdict_filter,json=verdictFilter,proto3,enum=integrity.v1.Verdict" json:"verdict_filter,omitempty"` // optional; VERDICT_UNKNOWN = no filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_api_proto_integrity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetSinceNs() uint64 {
	if x != nil {
		return x.SinceNs
	}
	return 0
}

func (x *ListEventsRequest) GetVerdictFilter() Verdict {
	if x != nil {
		return x.VerdictFilter
	}
	return Verdict_VERDICT_UNKNOWN
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ExecEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_api_proto_integrity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{5}
}

func (x *ListEventsResponse) GetEvents() []*ExecEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type WhitelistEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        []byte                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // optional, informational
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"` // optional, why it was added
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistEntry) Reset() {
	*x = WhitelistEntry{}
	mi := &file_api_proto_integrity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistEntry) ProtoMessage() {}

func (x *WhitelistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistEntry.ProtoReflect.Descriptor instead.
func (*WhitelistEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{6}
}

func (x *WhitelistEntry) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *WhitelistEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WhitelistEntry) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type WhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistResponse) Reset() {
	*x = WhitelistResponse{}
	mi := &file_api_proto_integrity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistResponse) ProtoMessage() {}

func (x *WhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistResponse.ProtoReflect.Descriptor instead.
func (*WhitelistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{7}
}

func (x *WhitelistResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *WhitelistResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        []byte                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWhitelistRequest) Reset() {
	*x = RemoveWhitelistRequest{}
	mi := &file_api_proto_integrity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistRequest) ProtoMessage() {}

func (x *RemoveWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistRequest.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveWhitelistRequest) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type ListWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWhitelistRequest) Reset() {
	*x = ListWhitelistRequest{}
	mi := &file_api_proto_integrity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWhitelistRequest) ProtoMessage() {}

func (x *ListWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWhitelistRequest.ProtoReflect.Descriptor instead.
func (*ListWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{9}
}

type ListWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*WhitelistEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWhitelistResponse) Reset() {
	*x = ListWhitelistResponse{}
	mi := &file_api_proto_integrity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWhitelistResponse) ProtoMessage() {}

func (x *ListWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWhitelistResponse.ProtoReflect.Descriptor instead.
func (*ListWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{10}
}

func (x *ListWhitelistResponse) GetEntries() []*WhitelistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_api_proto_integrity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{11}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventsPerSec  float64                `protobuf:"fixed64,1,opt,name=events_per_sec,json=eventsPerSec,proto3" json:"events_per_sec,omitempty"`
	EventsTotal   uint64                 `protobuf:"varint,2,opt,name=events_total,json=eventsTotal,proto3" json:"events_total,omitempty"`
	EventsBlocked uint64                 `protobuf:"varint,3,opt,name=events_blocked,json=eventsBlocked,proto3" json:"events_blocked,omitempty"`
	WhitelistSize uint64                 `protobuf:"varint,4,opt,name=whitelist_size,json=whitelistSize,proto3" json:"whitelist_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_integrity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_integrity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_integrity_proto_rawDescGZIP(), []int{12}
}

func (x *StatsResponse) GetEventsPerSec() float64 {
	if x != nil {
		return x.EventsPerSec
	}
	return 0
}

func (x *StatsResponse) GetEventsTotal() uint64 {
	if x != nil {
		return x.EventsTotal
	}
	return 0
}

func (x *StatsResponse) GetEventsBlocked() uint64 {
	if x != nil {
		return x.EventsBlocked
	}
	return 0
}

func (x *StatsResponse) GetWhitelistSize() uint64 {
	if x != nil {
		return x.WhitelistSize
	}
	return 0
}

var File_api_proto_integrity_proto protoreflect.FileDescriptor

const file_api_proto_integrity_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/integrity.proto\x12\fintegrity.v1\"\xee\x01\n" +
	"\tExecEvent\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x12\n" +
	"\x04comm\x18\x04 \x01(\tR\x04comm\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\fR\x06sha256\x12/\n" +
	"\averdict\x18\a \x01(\x0e2\x15.integrity.v1.VerdictR\averdict\x12!\n" +
	"\ftrust_reason\x18\b \x01(\tR\vtrustReason\"\x0f\n" +
	"\rStatusRequest\"\xe1\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x19\n" +
	"\buptime_s\x18\x02 \x01(\x04R\auptimeS\x12\x1f\n" +
	"\vtpm_present\x18\x03 \x01(\bR\n" +
	"tpmPresent\x12\x1b\n" +
	"\ttpm_state\x18\x04 \x01(\tR\btpmState\x12!\n" +
	"\fevents_total\x18\x05 \x01(\x04R\veventsTotal\x12%\n" +
	"\x0eevents_blocked\x18\x06 \x01(\x04R\reventsBlocked\x12\x12\n" +
	"\x04mode\x18\a \x01(\tR\x04mode\"\x0f\n" +
	"\rStreamRequest\"\x82\x01\n" +
	"\x11ListEventsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x19\n" +
	"\bsince_ns\x18\x02 \x01(\x04R\asinceNs\x12<\n" +
	"\x0everdict_filter\x18\x03 \x01(\x0e2\x15.integrity.v1.VerdictR\rverdictFilter\"E\n" +
	"\x12ListEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.integrity.v1.ExecEventR\x06events\"P\n" +
	"\x0eWhitelistEntry\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\fR\x06sha256\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"=\n" +
	"\x11WhitelistResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x16RemoveWhitelistRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\fR\x06sha256\"\x16\n" +
	"\x14ListWhitelistRequest\"O\n" +
	"\x15ListWhitelistResponse\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.integrity.v1.WhitelistEntryR\aentries\"\x0e\n" +
	"\fStatsRequest\"\xa6\x01\n" +
	"\rStatsResponse\x12$\n" +
	"\x0eevents_per_sec\x18\x01 \x01(\x01R\feventsPerSec\x12!\n" +
	"\fevents_total\x18\x02 \x01(\x04R\veventsTotal\x12%\n" +
	"\x0eevents_blocked\x18\x03 \x01(\x04R\reventsBlocked\x12%\n" +
	"\x0ewhitelist_size\x18\x04 \x01(\x04R\rwhitelistSize*t\n" +
	"\aVerdict\x12\x13\n" +
	"\x0fVERDICT_UNKNOWN\x10\x00\x12\x11\n" +
	"\rVERDICT_ALLOW\x10\x01\x12\x11\n" +
	"\rVERDICT_BLOCK\x10\x02\x12\x16\n" +
	"\x12VERDICT_QUARANTINE\x10\x03\x12\x16\n" +
	"\x12VERDICT_SUSPICIOUS\x10\x042\xbb\x04\n" +
	"\x10IntegrityService\x12F\n" +
	"\tGetStatus\x12\x1b.integrity.v1.StatusRequest\x1a\x1c.integrity.v1.StatusResponse\x12F\n" +
	"\fStreamEvents\x12\x1b.integrity.v1.StreamRequest\x1a\x17.integrity.v1.ExecEvent0\x01\x12O\n" +
	"\n" +
	"ListEvents\x12\x1f.integrity.v1.ListEventsRequest\x1a .integrity.v1.ListEventsResponse\x12M\n" +
	"\fAddWhitelist\x12\x1c.integrity.v1.WhitelistEntry\x1a\x1f.integrity.v1.WhitelistResponse\x12X\n" +
	"\x0fRemoveWhitelist\x12$.integrity.v1.RemoveWhitelistRequest\x1a\x1f.integrity.v1.WhitelistResponse\x12X\n" +
	"\rListWhitelist\x12\".integrity.v1.ListWhitelistRequest\x1a#.integrity.v1.ListWhitelistResponse\x12C\n" +
	"\bGetStats\x12\x1a.integrity.v1.StatsRequest\x1a\x1b.integrity.v1.StatsResponseB>Z<github.com/sulaiman3352/integrity-framework/daemon/pkg/pb;pbb\x06proto3"

var (
	file_api_proto_integrity_proto_rawDescOnce sync.Once
	file_api_proto_integrity_proto_rawDescData []byte
)

func file_api_proto_integrity_proto_rawDescGZIP() []byte {
	file_api_proto_integrity_proto_rawDescOnce.Do(func() {
		file_api_proto_integrity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_integrity_proto_rawDesc), len(file_api_proto_integrity_proto_rawDesc)))
	})
	return file_api_proto_integrity_proto_rawDescData
}

var file_api_proto_integrity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_integrity_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_integrity_proto_goTypes = []any{
	(Verdict)(0),                   // 0: integrity.v1.Verdict
	(*ExecEvent)(nil),              // 1: integrity.v1.ExecEvent
	(*StatusRequest)(nil),          // 2: integrity.v1.StatusRequest
	(*StatusResponse)(nil),         // 3: integrity.v1.StatusResponse
	(*StreamRequest)(nil),          // 4: integrity.v1.StreamRequest
	(*ListEventsRequest)(nil),      // 5: integrity.v1.ListEventsRequest
	(*ListEventsResponse)(nil),     // 6: integrity.v1.ListEventsResponse
	(*WhitelistEntry)(nil),         // 7: integrity.v1.WhitelistEntry
	(*WhitelistResponse)(nil),      // 8: integrity.v1.WhitelistResponse
	(*RemoveWhitelistRequest)(nil), // 9: integrity.v1.RemoveWhitelistRequest
	(*ListWhitelistRequest)(nil),   // 10: integrity.v1.ListWhitelistRequest
	(*ListWhitelistResponse)(nil),  // 11: integrity.v1.ListWhitelistResponse
	(*StatsRequest)(nil),           // 12: integrity.v1.StatsRequest
	(*StatsResponse)(nil),          // 13: integrity.v1.StatsResponse
}
var file_api_proto_integrity_proto_depIdxs = []int32{
	0,  // 0: integrity.v1.ExecEvent.verdict:type_name -> integrity.v1.Verdict
	0,  // 1: integrity.v1.ListEventsRequest.verdict_filter:type_name -> integrity.v1.Verdict
	1,  // 2: integrity.v1.ListEventsResponse.events:type_name -> integrity.v1.ExecEvent
	7,  // 3: integrity.v1.ListWhitelistResponse.entries:type_name -> integrity.v1.WhitelistEntry
	2,  // 4: integrity.v1.IntegrityService.GetStatus:input_type -> integrity.v1.StatusRequest
	4,  // 5: integrity.v1.IntegrityService.StreamEvents:input_type -> integrity.v1.StreamRequest
	5,  // 6: integrity.v1.IntegrityService.ListEvents:input_type -> integrity.v1.ListEventsRequest
	7,  // 7: integrity.v1.IntegrityService.AddWhitelist:input_type -> integrity.v1.WhitelistEntry
	9,  // 8: integrity.v1.IntegrityService.RemoveWhitelist:input_type -> integrity.v1.RemoveWhitelistRequest
	10, // 9: integrity.v1.IntegrityService.ListWhitelist:input_type -> integrity.v1.ListWhitelistRequest
	12, // 10: integrity.v1.IntegrityService.GetStats:input_type -> integrity.v1.StatsRequest
	3,  // 11: integrity.v1.IntegrityService.GetStatus:output_type -> integrity.v1.StatusResponse
	1,  // 12: integrity.v1.IntegrityService.StreamEvents:output_type -> integrity.v1.ExecEvent
	6,  // 13: integrity.v1.IntegrityService.ListEvents:output_type -> integrity.v1.ListEventsResponse
	8,  // 14: integrity.v1.IntegrityService.AddWhitelist:output_type -> integrity.v1.WhitelistResponse
	8,  // 15: integrity.v1.IntegrityService.RemoveWhitelist:output_type -> integrity.v1.WhitelistResponse
	11, // 16: integrity.v1.IntegrityService.ListWhitelist:output_type -> integrity.v1.ListWhitelistResponse
	13, // 17: integrity.v1.IntegrityService.GetStats:output_type -> integrity.v1.StatsResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_integrity_proto_init() }
func file_api_proto_integrity_proto_init() {
	if File_api_proto_integrity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_integrity_proto_rawDesc), len(file_api_proto_integrity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_integrity_proto_goTypes,
		DependencyIndexes: file_api_proto_integrity_proto_depIdxs,
		EnumInfos:         file_api_proto_integrity_proto_enumTypes,
		MessageInfos:      file_api_proto_integrity_proto_msgTypes,
	}.Build()
	File_api_proto_integrity_proto = out.File
	file_api_proto_integrity_proto_goTypes = nil
	file_api_proto_integrity_proto_depIdxs = nil
}
